"""empty message

Revision ID: 661e04faa942
Revises: 697e7e156219
Create Date: 2017-03-11 11:52:00.558149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '661e04faa942'
down_revision = '697e7e156219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UsersLCAutoInvestParameters')
    op.add_column('UsersLCAccountInfo', sa.Column('auto_invest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UsersLCAccountInfo', 'auto_invest')
    op.create_table('UsersLCAutoInvestParameters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"UsersLCAutoInvestParameters_id_seq"\'::regclass)'), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_default_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_default_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_int_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_int_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_loan_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_loan_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'Users.id'], name=u'UsersLCAutoInvestParameters_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'UsersLCAutoInvestParameters_pkey')
    )
    # ### end Alembic commands ###
