"""empty message

Revision ID: 697e7e156219
Revises: 
Create Date: 2017-03-06 12:49:31.089656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697e7e156219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'Users_stripe_id_key', 'Users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'Users_stripe_id_key', 'Users', ['stripe_id'])
    # ### end Alembic commands ###
