"""empty message

Revision ID: b23cf78bfb9f
Revises: 
Create Date: 2017-02-12 16:52:23.874697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23cf78bfb9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('stripe_id', sa.String(length=100), nullable=True))
    op.drop_constraint(u'Users_stripeId_key', 'Users', type_='unique')
    op.create_unique_constraint(None, 'Users', ['stripe_id'])
    op.drop_column('Users', 'stripeId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('stripeId', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Users', type_='unique')
    op.create_unique_constraint(u'Users_stripeId_key', 'Users', ['stripeId'])
    op.drop_column('Users', 'stripe_id')
    # ### end Alembic commands ###
